apiVersion: v1
kind: Secret
metadata:
  name: kc-postgres-admin-password
type: Opaque
stringData:
  # password: __POSTGRES_PASSWORD__
  password: lab-kcadmin-1999

---

apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin-password
type: Opaque
stringData:
  # KEYCLOAK_PASSWORD: __KEYCLOAK_PASSWORD__
  KEYCLOAK_PASSWORD: lab-kcadmin-1999